# Copyright 2020 Major League Baseball
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# centos7 base image
FROM centos:7 as base

# Add Circonus repository
ADD ./buildtools/el7/el7-Circonus.repo /etc/yum.repos.d/Circonus.repo

# Install the things we need
RUN yum -y update && \
  yum clean all && \
  yum -y install \
    sudo \
    git \
    gcc \
    gcc-c++ \
    automake \
    autoconf \
    circonus-field-ck \
    circonus-platform-library-curl \
    circonus-platform-library-jlog \
    circonus-platform-library-libcircllhist \
    circonus-platform-library-libmtev \
    circonus-platform-library-libssh2 \
    circonus-platform-library-uuid \
    circonus-platform-library-jemalloc \
    lapack-devel \
    librdkafka-devel \
    libxml2-devel \
    libxslt-devel \
    ncurses-devel \
    openssl-devel \
    rsync \
    wget \
    zlib-devel && \
    yum clean all && \
    rm -rf /var/cache/yum

# Add EPEL
RUN wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&  rpm -ivh epel-release-latest-7.noarch.rpm
RUN yum -y update && \
  yum clean all && \
  yum -y install \
    gflags-devel \
    gtest-devel \
    libtool \
    pkgconfig \
    curl \
    golang \
    cmake3


RUN git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc && \
    cd grpc && \
    git submodule update --init && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake3 \
      -DCMAKE_BUILD_TYPE=Release \
      -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DgRPC_SSL_PROVIDER=package \
      -S ../.. \
      -B `pwd` && \
    make -j4 install && \
    cd / && \
    rm -rf grpc

CMD ["bash"]