apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

data:
  tm.conf.b64: {{ (tpl (.Files.Get "configs/tm.tpl") .) | b64enc }}
